scan_filter_chain:
  # - name: filter1
  #   type: laser_filters/LaserScanAngularBoundsFilter
  #   params: {lower_angle: 0.21, upper_angle: 1.34}

  # - name: filter2
  #   type: laser_filters/LaserScanAngularBoundsFilter
  #   params: {lower_angle: 1.66, upper_angle: 2.97}

  # - name: filter3
  #   type: laser_filters/LaserScanAngularBoundsFilter
  #   params: {lower_angle: -2.97, upper_angle: -1.66}

  # - name: filter4
  #   type: laser_filters/LaserScanAngularBoundsFilter
  #   params: {lower_angle: -1.34, upper_angle: -0.21}

  - name: filter1
    type: laser_filters/LaserScanAngularBoundsFilterInPlace
    params: {lower_angle: -0.21, upper_angle: 0.21}

  - name: filter2
    type: laser_filters/LaserScanAngularBoundsFilterInPlace
    params: {lower_angle: 1.3, upper_angle: 1.7}

  - name: filter3
    type: laser_filters/LaserScanAngularBoundsFilterInPlace
    params: {lower_angle: 2.97, upper_angle: -2.97}

  - name: filter4
    type: laser_filters/LaserScanAngularBoundsFilterInPlace
    params: {lower_angle: -1.7, upper_angle: -1.3}


