robot_radius: 0.2

laser_layer:
  obstacle_range: 8.0
  raytrace_range: 13.0
  max_obstacle_height: 1.0
  track_unknown_space: true
  observation_sources: rplidar
  rplidar:
    data_type: LaserScan
    topic: /lidar_undistortion/scan
    marking: true
    clearing: true
    inf_is_valid: false

inflation_layer:
  cost_scaling_factor: 0.7
  inflation_radius: 0.3
