local_costmap:
  global_frame: map
  robot_base_frame: locobot/imu_link
  update_frequency: 5.0
  publish_frequency: 5.0
  rolling_window: true
  width: 2.0
  height: 2.0
  resolution: 0.01
  plugins:
  - {name: laser_layer, type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
