controller_frequency: 10
controller_patience: 3

planner_frequency: 1
planner_patience: 5

oscillation_timeout: 10
oscillation_distance: 0.2

base_global_planner: global_planner/GlobalPlanner
base_local_planner: teb_local_planner/TebLocalPlannerROS

# base_global_planner: "navfn/NavfnROS"
# base_local_planner: "base_local_planner/TrajectoryPlannerROS"

